version: '3'
services:
  postgres:
    image: 'postgres:9.6-alpine'
    environment:
      POSTGRES_USER: 'crowdai'
      POSTGRES_PASSWORD: 'apassword'
    ports:
      - '5432:5432'
    volumes:
      - 'postgres:/var/lib/postgresql/data'

  redis:
    image: 'redis:3.2-alpine'
    command: redis-server --requirepass apassword
    ports:
      - '6379:6379'
    volumes:
      - 'redis:/data'

  web:
    depends_on:
      - 'postgres'
      - 'redis'
    build: .
    command: foreman start -f Procfile.dev
    volumes:
      - .:/app
    ports:
      - "3000:3000"
      - "8080:8080"

volumes:
  redis:
  postgres:
